# 1. Handling numerical data for trajectory calculations and simulations.

1. Create a numpy array to represent time from 0 to 100.
2. Create a numpy array to represent altitude in meters during the launch phase. The altitude starts at 0 meters and increases linearly with time by 100 meters per second.
3. Calculate the velocity array using the altitude array. Assume constant acceleration (9.81 m/s^2) during the launch phase.
4. Calculate the acceleration array using a constant acceleration value of 9.81 m/s^2.
5. Print the shape and data type of each generated numpy array.

In [13]:
gravity_acceleration = 9.81   # constant acceleration due to gravity in m/s^2

In [25]:
import numpy as np

time = np.arange(0, 101)

print("Time")
print("------")
print(time)
print()

Time
------
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [24]:
altitude = np.zeros(time.shape)
altitude += time * 100

print("Altitude")
print("---------")
print(altitude)
print()

Altitude
---------
[    0.   100.   200.   300.   400.   500.   600.   700.   800.   900.
  1000.  1100.  1200.  1300.  1400.  1500.  1600.  1700.  1800.  1900.
  2000.  2100.  2200.  2300.  2400.  2500.  2600.  2700.  2800.  2900.
  3000.  3100.  3200.  3300.  3400.  3500.  3600.  3700.  3800.  3900.
  4000.  4100.  4200.  4300.  4400.  4500.  4600.  4700.  4800.  4900.
  5000.  5100.  5200.  5300.  5400.  5500.  5600.  5700.  5800.  5900.
  6000.  6100.  6200.  6300.  6400.  6500.  6600.  6700.  6800.  6900.
  7000.  7100.  7200.  7300.  7400.  7500.  7600.  7700.  7800.  7900.
  8000.  8100.  8200.  8300.  8400.  8500.  8600.  8700.  8800.  8900.
  9000.  9100.  9200.  9300.  9400.  9500.  9600.  9700.  9800.  9900.
 10000.]


In [23]:
# m/s (m/s^2 * s = m/s; 9.81 m/s^2 * time array (s))
velocity = 9.81 * time

print("Velocity")
print("----------")
print(velocity)
print()

Velocity
--------
[  0.     9.81  19.62  29.43  39.24  49.05  58.86  68.67  78.48  88.29
  98.1  107.91 117.72 127.53 137.34 147.15 156.96 166.77 176.58 186.39
 196.2  206.01 215.82 225.63 235.44 245.25 255.06 264.87 274.68 284.49
 294.3  304.11 313.92 323.73 333.54 343.35 353.16 362.97 372.78 382.59
 392.4  402.21 412.02 421.83 431.64 441.45 451.26 461.07 470.88 480.69
 490.5  500.31 510.12 519.93 529.74 539.55 549.36 559.17 568.98 578.79
 588.6  598.41 608.22 618.03 627.84 637.65 647.46 657.27 667.08 676.89
 686.7  696.51 706.32 716.13 725.94 735.75 745.56 755.37 765.18 774.99
 784.8  794.61 804.42 814.23 824.04 833.85 843.66 853.47 863.28 873.09
 882.9  892.71 902.52 912.33 922.14 931.95 941.76 951.57 961.38 971.19
 981.  ]


In [22]:
acceleration = np.full(time.shape, gravity_acceleration)

print("Acceleration")
print("--------------")
print(acceleration)
print()

Acceleration
--------------
[9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81
 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81
 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81
 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81
 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81
 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81
 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81 9.81
 9.81 9.81 9.81]


In [29]:
print("Shape of time array: ", time.shape)
print("Data type of time array: ", time.dtype)
print()

print("Shape of altitude array: ", altitude.shape)
print("Data type of altitude array: ", altitude.dtype)
print()

print("Shape of velocity array: ", velocity.shape)
print("Data type of velocity array: ", velocity.dtype)
print()

print("Shape of acceleration array: ", acceleration.shape)
print("Data type of acceleration array: ", acceleration.dtype)
print()

Shape of time array:  (101,)
Data type of time array:  int32

Shape of altitude array:  (101,)
Data type of altitude array:  float64

Shape of velocity array:  (101,)
Data type of velocity array:  float64

Shape of acceleration array:  (101,)
Data type of acceleration array:  float64



# Random Number Generation

Some random methods to remember:
<br>
- <code>random.rand()</code> : returns a random float between 0 and 1 
<br>
- <code>random.randn()</code> : returns a sample from the "standard normal" distribution (mean = 0, standard deviation = 1)
<br>
- <code>random.randint()</code> : returns random integers from low(inclusive) to high(exclusive)

In [49]:
# generates a 1D array of 5 random numbers between 0 and 1
rand_arr_1d = np.random.rand(5)
print("1D array of random numbers between 0 and 1: ")
print(rand_arr_1d)
print()

# generates a 2D array of 2 rows and 3 columns of  random numbers between 0 and 1
rand_arr_2d = np.random.rand(2, 3)
print("2D array of 2 rows and 3 columns of random numbers between 0 and 1: ")
print(rand_arr_2d)
print()

1D array of random numbers between 0 and 1: 
[0.97809248 0.56365746 0.14805155 0.39887475 0.90114728]

2D array of 2 rows and 3 columns of random numbers between 0 and 1: 
[[0.36207764 0.70128812 0.89581723]
 [0.85348533 0.45752205 0.89215991]]


In [50]:
randn_arr_1d = np.random.randn(5)
print("1D array of 5 random numbers from a standard normal distribution: ")
print(randn_arr_1d)
print()

randn_arr_2d = np.random.randn(2, 3)
print("2D array with 2 rows and 3 columns of random numbers from a standard normal distribution: ")
print(randn_arr_2d)
print()

1D array of 5 random numbers from a standard normal distribution: 
[-0.71750879  0.75723174  0.22174     0.88718209  1.04401801]

2D array with 2 rows and 3 columns of random numbers from a standard normal distribution: 
[[-1.9221408   1.7976953   1.4126565 ]
 [ 0.38844861 -1.97097048 -0.1313334 ]]


In [51]:
randint_arr_1d = np.random.randint(0, 10, size=5)
print("1D array of 5 random numbers from 0 to 9: ")
print(randint_arr_1d)
print()

randint_arr_2d = np.random.randint(0, 100, size=(2,3))
print("2D array of 2 rows and 3 columns of random numbers from 0 to 99: ")
print(randint_arr_2d)

1D array of 5 random numbers from 0 to 9: 
[6 9 4 9 3]

2D array of 2 rows and 3 columns of random numbers from 0 to 99: 
[[50 34 96]
 [48 70 75]]


# Array Comparisons and Boolean Operations

np.where(condition, [x, y])
- np.where() : return elements from x or y depending on condition

In [59]:
arr = np.array([1, 2, 3, 4, 5])

# find indices where the element is greater than 2
indices = np.where(arr > 2)
print("Indices where the elements are greater than 2: ", indices)
print()

Indices where the elements are greater than 2:  (array([2, 3, 4], dtype=int64),)



- <code>ndarray.any()</code> : returns True if ANY element in the array evaluates to True, otherwise False
- <code>ndarray.all()</code> : returns True if ALL elements in the array evaluate to True, otherwise False

In [57]:
arr = np.array([False, True, False, True])

any_true = arr.any()
print("Any values that are True: ", any_true)
print()

all_true = arr.all()
print("All values that are True: ", all_true)
print()

Any values that are True:  True

All values that are True:  False



- <code>np.logical_and()</code> : performs element-wise logical AND operation between two arrays
- <code>np.logical_or()</code> : performs element-wise logical OR operation between two arrays
- <code>np.logical_not()</code> : performs element-wise logical NOT operation on an array

In [66]:
arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

# logical AND
result_and = np.logical_and(arr1, arr2)
print("Element-wise logical AND: ", result_and)
print()

# logical OR
result_or = np.logical_or(arr1, arr2)
print("Element-wise logical OR: ", result_or)
print()

# logical NOT
result_not = np.logical_not(arr1)
print("Element-wise logical NOT: ", result_not)
print()

Element-wise logical AND:  [ True False False False]

Element-wise logical OR:  [ True  True  True False]

Element-wise logical NOT:  [False False  True  True]



# Array Manipulation

<h2>Indexing</h2>

- Access individual elements using square brackets <code>[]</code>

In [68]:
arr = np.array([1,2,3,4,5])

print("Element at index 0: ", arr[0])
print("Element at index 3: ", arr[3])
print("Element at index -1: ", arr[-1])
print()

Element at index 0:  1
Element at index 3:  4
Element at index -1:  5



<h2>Slicing</h2>

- Array slicing in NumPy allows you to extract subarrays from NumPy arrays using colon <code>:</code> notation

In [73]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("First 3 elements: ", arr[:3])
print("Elements from index 3 to 6: ", arr[3:7])
print("Even-indexed elements: ", arr[::2])
print("Reverse the array: ", arr[::-1])

First 3 elements:  [1 2 3]
Elements from index 3 to 6:  [4 5 6 7]
Even-indexed elements:  [1 3 5 7 9]
Reverse the array:  [10  9  8  7  6  5  4  3  2  1]


<h2>Appending and Concatenating Arrays</h2>

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print("Array 1: ", arr1)
print("Array 2: ", arr2)
print()

# append arr2 to arr1
appended_arr = np.append(arr1, arr2)
print("Appended array: ", appended_arr)

# concatenate arrays along axis 0 (along rows)
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated array along axis 0: ", concatenated_arr)
print()

<h2>Flattening Arrays</h2>

In [80]:
arr = np.array([[1,2,3], [4,5,6]])
flattened_arr = arr.flatten()

print("Arrays in arr: ")
print(arr)
print("Flattened array: ", flattened_arr)

Arrays in arr: 
[[1 2 3]
 [4 5 6]]
Flattened array:  [1 2 3 4 5 6]


# 2. Mission Profiling

<h2>Objectives: </h2>
1. Generate simulated altitude, velocity, and acceleration data by using random number generation with NumPy.
<br>
2. Assume that the flight data consists of 1000 data points for altitude, velocity, and acceleration.
<br>
3. Perform array indexing and slicing to extract subsets of data for analysis.
<br>
4. Use array comparisons and conditional methods to identify critical points:

 - Critical altitude: Altitude above 5000 meters.
 - Critical velocity: Velocity greater than 300 meters per second.
 - Critical acceleration: Acceleration less than -9.8 meters per second squared (indicating deceleration).
   
<br>
5. Concatenate arrays representing critical points to an array and print it out!

In [87]:
import numpy as np

altitude = np.random.uniform(0, 10000, size=1000)
velocity = np.random.uniform(0, 400, size=1000)
acceleration = np.random.uniform(-20, 20, size=1000)

critical_altitude = altitude[altitude > 5000]
critical_velocity = velocity[velocity > 300]
critical_acceleration = acceleration[acceleration < -9.8]

flight_profile = np.concatenate((critical_altitude, critical_velocity, critical_acceleration))

print("Flight Profile")
print(flight_profile)

Flight Profile
[6557.38147656 5185.42794182 8941.6488122  ...  -11.56020536  -15.27514062
  -14.0175371 ]
